import numpy as np
a= np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4]])
print("a的形状：",a.shape)
print("a的类型：",a.dtype)
print("a的维度：",a.ndim)
b=np.arange(12).reshape(3,4)
print(b.dtype)
print(b.shape)
print(b.ndim)
print(np.zeros((3,3),dtype=int))
print(np.ones((3,3)))
print(np.full((2,3),7))